### ISSUE TITLE
Suggestion: Add alternative glow chalk recipe

### ISSUE THREAD

**Issue by EGOIST1372** [DaFuqs/Chalk#11]
Add alternative glow chalk recipe (screenshot example)
![image](https://user-images.githubusercontent.com/86555131/153726710-1fc825fe-1a19-4da8-b93e-cfe38b4d5798.png)
thanks in advance

**Comment by DaFuqs** [comment]
I see where you are coming from, but I am not feeling that one from a gameplay perspective, sorry

**Comment by EGOIST1372** [comment]
understandable :D
