### ISSUE TITLE
Lighting bug is still not resolved

### ISSUE THREAD

**Issue by EGOIST1372** [DaFuqs/Chalk#13]
The bug is still there
![image](https://user-images.githubusercontent.com/86555131/154959464-ea79b860-a277-4d64-ab74-ea6ab9c569e6.png)

I wasn't sure what to do since that issue was closed #12  so I created a new one

**Comment by EGOIST1372** [comment]
even hinges are showing this glitch
![image](https://user-images.githubusercontent.com/86555131/154966766-6f81a8fb-f190-4e77-87d9-71b1e43835e9.png)

**Comment by EGOIST1372** [comment]
trapdoors seems ok but doors have the glitch
![image](https://user-images.githubusercontent.com/86555131/155854993-07346b20-4cb5-4470-9407-042d3a0ea396.png)

**Comment by DaFuqs** [comment]
Fixed in 2.0.0
