### ISSUE TITLE
Drawing/Writing?

### ISSUE THREAD

**Issue by sormgoma** [DaFuqs/Chalk#15]
Would it be possible to introduce drawing functionality? like that you can draw whatever you'd like on the block. Maybe the option to draw in 32x32 would also be nice to be able to write on blocks.

**Comment by DaFuqs** [comment]
I have thought about it. While that would be cool, that definitely would not match that vanilla feel I am aiming for.

**Comment by DaFuqs** [comment]
Well, it could make a good addon mod. If someone wants to contribute: sure.
