### ISSUE TITLE
Set light level of glow chalk to 0 to solve light bug and vanilla parity

### ISSUE THREAD

**Issue by EGOIST1372** [DaFuqs/Chalk#16]
Hi
I like to suggest that if you set the light level that emits from glow chalk to zero so it just glow like a glow text on signs it would be more vanilla like (it won't interfere with spawning rules in 1.18.2 that requires light level 0) and would solve #13 issue all together.
as you can see in first screenshot it emits light
![image](https://user-images.githubusercontent.com/86555131/161801940-966d1d5c-605d-46e8-8b9d-788f8edc470f.png)
and this is the lighting bug
![image](https://user-images.githubusercontent.com/86555131/161802179-0b408caa-83e2-483e-b1b9-36ff2ef4330c.png)

thanks in advance
love your work <3

**Comment by DaFuqs** [comment]
now this is why it looks so bad. Come on, vanilla!

Ty very much for the hint! :)

**Comment by DaFuqs** [comment]
Fixed in 2.0.0

**Comment by DaFuqs** [comment]
Vanilla really does not handle transparent, light emitting blocks well

**Comment by EGOIST1372** [comment]
https://minecraft.fandom.com/wiki/Glow_Ink_Sac#Signs
"Glow ink sacs can be used on [signs](https://minecraft.fandom.com/wiki/Sign) to make their text brighter in low light levels. This also adds an outline around the text on the sign, the color of which is based on the color of the sign's text. **The text does not emit any light**, it is only more visible in darkness, similarly to the eyes of Spiders and Endermen."
![image](https://user-images.githubusercontent.com/86555131/161963469-26ae58b1-b8d2-4d2d-bc63-ebcb723b6fc4.png)

https://minecraft.fandom.com/wiki/Item_Frame#Glow_Item_Frames
When an item is placed inside a glow item frame, it appears to glow, even though it does **not emit any light.**
![image](https://user-images.githubusercontent.com/86555131/161963348-e321cf2c-c3f2-40c4-9c86-5dd0d9d1491a.png)

> 
Well, setting the light level to 0 does not make the chalk emissive anymore.

I meant these two examples that I mentioned above

**Comment by DaFuqs** [comment]
Ooooh, I understand now. Ty for claring this up.
The text and on Signs and Item Frames are actually rendered very differently from blocks to make them more dynamic as they need to be for storing all kinds of text and items.
Applying this logic to Glow Chalk would give quite a hit to FPS, so I rather not go that route.

**Comment by EGOIST1372** [comment]
yeah just to be sure I tested the performance for FPS
![image](https://user-images.githubusercontent.com/86555131/162013053-6d6a2c1c-e1aa-4357-ae99-29c0c1aaafe8.png)

 with this many glow banners my FPS didn't change after and before adding glow ink to banners.
I hope this info helps.

**Comment by EGOIST1372** [comment]
Bigger sample size
Before
![image](https://user-images.githubusercontent.com/86555131/162017037-ec78dc2b-3687-4bbc-ab58-7f18b9ed6dd3.png)

After
![image](https://user-images.githubusercontent.com/86555131/162017167-0027d720-98b9-4667-96a8-52bbb18297a9.png)

**Comment by DaFuqs** [comment]
I tried it out in the current snapshots again, but it seems the lighting issues in vanilla with mushrooms and all seem unchanged, sadly.
