### ISSUE TITLE
Chalk marks erase solid partial blocks

### ISSUE THREAD

**Issue by dragonmaus** [DaFuqs/Chalk#19]
If you try to place a chalk mark on a block that is partially obscured by another partial block (slabs, stairs, doors, etc.), it will succeed and in the process delete the partial block.

I first noticed the issue with the 2.0.0+1.18.2 build, then tested with the latest code (and no other mods) and took the following screenshots:
![2022-05-12_00 28 47](https://user-images.githubusercontent.com/5817605/167992331-ffb56d14-5a46-498a-9ed1-1367d890baa6.png)
![2022-05-12_00 28 53](https://user-images.githubusercontent.com/5817605/167992345-4eb22e0f-e520-417c-b39f-34fd0dac3050.png)
![2022-05-12_00 29 03](https://user-images.githubusercontent.com/5817605/167992349-cde514f0-00d2-4f2b-99ec-5058d82ac0f3.png)
![2022-05-12_00 29 08](https://user-images.githubusercontent.com/5817605/167992353-3defcddf-7887-43ac-aa91-e30acd4949b3.png)

**Comment by DaFuqs** [comment]
Nice find! Thank you for reporting this. I will get that fixed.

**Comment by DaFuqs** [comment]
Fixed in 2.0.1 via https://github.com/DaFuqs/Chalk/commit/12d3bf988469de4bcfcf429293366c082d34e6a8
