### ISSUE TITLE
Impossible to draw arrows pointing up when located below Y0

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [DaFuqs/Chalk#2]
**MC** 1.17.1
**Fabric** loader 0.12.4; API 0.41.3
**Chalk** 1.0.1

To reproduce:

1. Create a world with extended height (using an official 1.18 preview datapack for example; I use [this one](https://www.planetminecraft.com/data-pack/caves-amp-cliffs-expansion-pack-20w20a-compatible/), which includes the official datapack)
2. Go below Y0 and try to draw an arrow pointing upwards

**Examples:**

Y0, pointing at the top center of a block:
![2021-11-02_20 14 49](https://user-images.githubusercontent.com/86702831/139938625-dc1b02f5-932b-4432-8a73-843cf4b5b0aa.png)

Y-1, pointing at the top center of a block:
![2021-11-02_20 15 00](https://user-images.githubusercontent.com/86702831/139939075-aa43c282-aba9-4410-ae56-6c734d469b2f.png)

Y0, pointing at the upper left corner of a block:
![2021-11-02_20 15 52](https://user-images.githubusercontent.com/86702831/139939223-c5c02292-6b46-4147-a86a-92401b5aca7c.png)

Y-1, pointing at the upper left corner of a block:
![2021-11-02_20 15 48](https://user-images.githubusercontent.com/86702831/139939696-95ab5609-3039-4b5b-958b-370ee0860f33.png)

**Comment by DaFuqs** [comment]
This should be an easy fix. Ty for the bug report!

**Comment by DaFuqs** [comment]
Fixed in 1.0.2 via 0b7579dd9981556c5627c537c38b0099b60a1e06
