### ISSUE TITLE
Option to disable Smoke Partikel

### ISSUE THREAD

**Issue by ardissaps** [DaFuqs/Chalk#21]
Thank you! (1.18.2)

**Comment by ardissaps** [comment]
also option to make glow chalk only glow, not emit light.

**Comment by DaFuqs** [comment]
> Option to disable Smoke Partikel

sure

> make glow chalk only glow, not emit light.

Not possible without a great hit to performance

**Comment by mclegoman** [comment]
I've added an option to my 1.20 (pre-releases) pull-request for disabling the smoke particle.
