### ISSUE TITLE
suggestion: Using an emissive layer for glowing chalk

### ISSUE THREAD

**Issue by GermanArtur** [DaFuqs/Chalk#27]
Block of glowing chalk has problems with the light rendering, since it has only 1 level of illumination:
![image](https://user-images.githubusercontent.com/64424996/210184861-4453831c-11a8-4586-872d-ed1ee19e7864.png)

Without smooth lighting:
![image](https://user-images.githubusercontent.com/64424996/210184875-cec82d0c-22a3-4dca-99d8-212ddcce3857.png)

I propose to remove the light emitting by the block and replace it with an emissive layer using the continuity mod:
![image](https://user-images.githubusercontent.com/64424996/210184866-b7fa987f-11fd-445e-9986-f6e63c92e7a5.png)

**Comment by DaFuqs** [comment]
Done for 1.19+
