### ISSUE TITLE
Coloured chalk recipes in the base version

### ISSUE THREAD

**Issue by Strubbelkopp** [DaFuqs/Chalk#28]
The recipes for the coloured chalks are contained in the base version of the mod, which'll spam your log with error messages saying that the item does not exist, if you don't have the coloured chalk addon installed:

Example: 
`Parsing error loading recipe chalk:crafting_table/blue_chalk`
`com.google.gson.JsonSyntaxException: Unknown item 'chalk:blue_chalk'`

**Comment by DaFuqs** [comment]
Fixed in 2.1.2 ✔️ 
Thank you lots for the heads up!
