### ISSUE TITLE
1.19.2 crash

### ISSUE THREAD

**Issue by netcore10** [DaFuqs/Chalk#31]
https://paste.atlauncher.com/view/cba56326-94b7-4b24-a2d4-5639fe2329ca

**Comment by DaFuqs** [comment]
Where do you get the impression that the crash is caused by chalk? o.O

> Critical injection failure: LVT in net/minecraft/class_634::method_11112(Lnet/minecraft/class_2604;)V has incompatible changes at opcode 62 in callback #arcanus:arcanus.mixins.json:client.ClientPlayNetworkHandlerMixin from mod arcanus

Looks like arcanus is the issue

**Comment by netcore10** [comment]
dang, it strangely only happened when chalk was added. - i suppose i have to pick between chalk or magic xD
