### ISSUE TITLE
Chalk marks delete replaceable blocks

### ISSUE THREAD

**Issue by bmollot** [DaFuqs/Chalk#34]
When making a chalk mark in the same block as a replaceable block the old block is deleted without dropping.

Replication:
1. Place a torch against a wall such that the ceiling is immediately above it.
2. Make a mark with chalk on the ceiling such that it occupies the same block as the torch.
3. The torch vanishes, and the mark is made.

What should probably happen:
One of
1. The torch is dropped
2. The mark is not made and the torch remains
3. The mark and torch are both present in the block (probably difficult)

**Comment by DaFuqs** [comment]
yes, definitely. I will change that. 1) sounds best

**Comment by DaFuqs** [comment]
done in 2.2.1
